import React from 'react';
import { Copy, ExternalLink } from 'lucide-react';

interface GroundingSource {
  web?: {
    title?: string;
    uri?: string;
  };
  title?: string;
  uri?: string;
}

interface ReportViewProps {
  title: string;
  content: string;
  groundingSources?: GroundingSource[];
  timestamp?: string;
}

export const ReportView: React.FC<ReportViewProps> = ({
  title,
  content,
  groundingSources = [],
  timestamp,
}) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopyReport = () => {
    const reportText = `${title}\n\n${content}\n\n${
      groundingSources.length > 0
        ? 'Sources:\n' +
          groundingSources
            .map((source) => {
              const sourceTitle = source.web?.title || source.title || 'Unknown';
              const sourceUri = source.web?.uri || source.uri || '#';
              return `- ${sourceTitle}: ${sourceUri}`;
            })
            .join('\n')
        : ''
    }`;

    navigator.clipboard.writeText(reportText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  // Safely extract source title and URI with nested property support
  const extractSourceInfo = (
    source: GroundingSource
  ): { title: string; uri: string } => {
    const title =
      source.web?.title ||
      source.title ||
      'Reference';
    const uri =
      source.web?.uri ||
      source.uri ||
      '#';
    return { title, uri };
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-lg">
      {/* Header */}
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">{title}</h1>
        {timestamp && (
          <p className="text-sm text-gray-500">
            Generated: {new Date(timestamp).toLocaleString()}
          </p>
        )}
      </div>

      {/* Copy Button */}
      <button
        onClick={handleCopyReport}
        className="mb-6 flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
      >
        <Copy size={16} />
        {copied ? 'Copied!' : 'Copy Report'}
      </button>

      {/* Content */}
      <div className="prose prose-sm max-w-none mb-8">
        <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
          {content}
        </p>
      </div>

      {/* Grounding Sources */}
      {groundingSources && groundingSources.length > 0 && (
        <div className="border-t pt-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">
            Sources
          </h2>
          <div className="space-y-3">
            {groundingSources.map((source, index) => {
              const { title: sourceTitle, uri: sourceUri } =
                extractSourceInfo(source);
              return (
                <div
                  key={index}
                  className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <ExternalLink
                    size={16}
                    className="text-blue-600 flex-shrink-0 mt-0.5"
                  />
                  <div className="flex-1 min-w-0">
                    <a
                      href={sourceUri}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 hover:text-blue-800 font-medium block truncate"
                    >
                      {sourceTitle}
                    </a>
                    <p className="text-xs text-gray-500 truncate">
                      {sourceUri}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="mt-8 pt-6 border-t text-center text-sm text-gray-500">
        <p>Report generated by FinPulse AI</p>
      </div>
    </div>
  );
};
